---
fixtures:
  repositories:
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
  symlinks:
    useradd: "#{source_dir}"
