---
fixtures:
  repositories:
    compliance_markup:
      repo: "https://github.com/simp/pupmod-simp-compliance_markup"
      branch: "testing_hotfix_06062019"
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
  symlinks:
    useradd: "#{source_dir}"
